pagarme/pagarme-php

lib/Pagarme/Address.php, lib/Pagarme/Bank_Account.php, lib/Pagarme/Card.php, lib/Pagarme/CardHashCommon.php, lib/Pagarme/Customer.php, lib/Pagarme/Error.php, lib/Pagarme/Exception.php, lib/Pagarme/Model.php, lib/Pagarme/Object.php, lib/Pagarme/PagarMe.php, lib/Pagarme/Phone.php, lib/Pagarme/Plan.php, lib/Pagarme/Recipient.php, lib/Pagarme/Request.php, lib/Pagarme/RestClient.php, lib/Pagarme/Set.php, lib/Pagarme/Subscription.php, lib/Pagarme/Transaction.php, lib/Pagarme/TransactionCommon.php, lib/Pagarme/Util.php, tests/PagarMe/Object.php, tests/PagarMe/Plan.php, tests/PagarMe/Set.php, tests/PagarMe/Subscription.php, tests/PagarMe/TestCase.php, tests/PagarMe/Transaction.php, tests/PagarMe/Util.php, tests/Pagarme.php
Adição de classes para trabalhar com Recipients e Bank Accounts
Usar a tag de fechamento do PHP deve ser omitida para não causar alguns possíveis erros (http://stackoverflow.com/questions/4410704/why-would-one-omit-the-close-tag)
Alterações simples de style do código
=> Adiciona Recipient e Bank Account na API + Adoção de algumas best practices

Pagarme.php, tests/PagarMe/Bank_Account.php, tests/PagarMe/Recipient.php, tests/PagarMe/TestCase.php, tests/Pagarme.php
Já haviam models que permitiam a criação/consulta por id/consulta de todos os recipientes e contas bancárias. Entretanto, eles não estavam `require`d no `Pagarme.php` no root.
Além disso, não haviam testes para esses dois modelos, que foram adicionados.
=> Adicionar Bank_Account e Recipient à biblioteca PHP

lib/Transaction/Request/BoletoTransactionRefund.php, lib/Transaction/TransactionHandler.php, tests/unit/Transaction/Request/BoletoTransactionRefundTest.php
`amount` is exclusive for credit card refunds.
=> Removing deprecated param

lib/Transfer/Request/TransferCreate.php, lib/Transfer/TransferHandler.php, tests/acceptance/TransferContext.php, tests/unit/Transfer/Request/TransferCreateTest.php
Use `BankAccount` class instead of scalar value. Same as #94.
=> Optional bank account value on transfer

lib/Recipient/RecipientHandler.php
recipientId was int, changed to string, according to the api's documentation. ref: https://docs.pagar.me/api/#objeto-recipient
PS.: Despite of being just cosmetic, some IDE's, like PHPStorm, relies on these PHPDoc to infer wheter the arguments are correct or not.
@xduh
=> Fixed get's phpdoc

lib/Transaction/TransactionHandler.php
On transactions via boleto, the postback_url parameter was not beeing set because of the array key name on **TransactionHandler** class.
=> HOTFIX: postback_url not being set in transactions via boleto

lib/Transaction/BoletoTransaction.php
Com este bugfix consegui fechar uma transação em boleto, no retorno não estava sendo capaz de capturar as propriedades boletoUrl e boletoBarcode referenciadas na issue: #128
=> Bugfix boleto properties (boletoUrl and boletoBarcode) do not exists

lib/Subscription/Request/CardSubscriptionCreate.php, tests/unit/Subscription/Request/CardSubscriptionCreateTest.php
Fixing subscrition by card_hash as described in #126.
=> Fixing subscrition by card_hash

lib/Subscription/Request/SubscriptionCreate.php, tests/unit/Subscription/Request/BoletoSubscriptionCreateTest.php, tests/unit/Subscription/Request/CardSubscriptionCreateTest.php
Conforme descrito na issue #137, a propriedade postbackUrl não estava sendo setada tanto para boleto quanto para cartão de crédito.
Esse PR visa solucionar esse problema assim como adicionar testes unitários para essa propriedade, garantindo que esse erro não volte a ocorrer.
=> Corrigindo postbackUrl não sendo setado

behat.yml, lib/BulkAnticipation/BulkAnticipationHandler.php, lib/BulkAnticipation/Request/BulkAnticipationCreate.php, tests/acceptance/BulkAnticipationContext.php, tests/acceptance/features/bulk_anticipation.feature, tests/unit/BulkAnticipation/BulkAnticipationHandlerTest.php, tests/unit/BulkAnticipation/Request/BulkAnticipationCreateTest.php
A propriedade utilizada anteriormente estava errada.
#150 
Criação de testes de comportamento utilizando behat para garantir a funcionalidade e correção dos testes unitários que verificavam se a propriedade errada tinha sido criada.
=> Corrigindo criação de antecipação com a propriedade build

lib/Transaction/Request/TransactionCapture.php, lib/Transaction/TransactionHandler.php, tests/unit/Transaction/Request/TransactionCaptureTest.php
Permite adicionar metadata no ato de captura de uma transação.
#157
- Testes manuais
- Testes unitários
=> Enabling metadata when capturing a pre-authorized transaction.

lib/PagarMe.php
Permite que seja possível passar informações no header das requisições feitas pela SDK.
Crie uma instância de `PagarMe\Sdk\PagarMe` passando um array de chave e valor como terceiro parâmetro do construtor, contendo as informações que devam ser passadas no header e faça o uso de métodos do SDK.
As informações passadas no terceiro parâmetro deveriam ser enviadas em todas as requisições.
Atualmente não é possível passar o terceiro parâmetro `$headers`.
=> Headers: Permitir que informações possam ser passadas no header das requisições feitas pela SDK.

lib/Card/CardHandler.php, lib/Card/Request/CardCreateFromHash.php, tests/unit/Card/Request/CardCreateFromHashTest.php
Adiciona o suporte à adição de cartões através de um `card_hash` gerado pela [Pagarme.js](https://github.com/pagarme/pagarme-js)
pagarme/pagarme-php#168
Criado teste unitário `lib/tests/unit/Card/Request/CardCreateFromHashRequest.php`.
Feito teste funcional utilizando a Pagarme.js, disponível no gist: https://gist.github.com/DfKimera/6312e8d65684b78e501d6e41d60fdbf4
Testes feitos com PHP 7.0.2 no macOS Sierra 10.12.4. Não contém código passível de incompatibilidade.
@xduh
=> Added support to adding a Card by its hash (pagarme/pagarme-php#168)

lib/Transaction/CreditCardTransaction.php, lib/Transaction/Request/CreditCardTransactionCreate.php, tests/unit/Transaction/Request/CreditCardTransactionCreateTest.php
Corrige passagem do parâmetro `async` nas transações de cartão de crédito
Adicionado teste automatizado
=> Fix async param fowarding

lib/Subscription/Request/SubscriptionCreate.php, tests/unit/Subscription/Request/BoletoSubscriptionCreateTest.php, tests/unit/Subscription/Request/CardSubscriptionCreateTest.php
Era obrigatório a população dos objetos Address e Phone para criar uma assinatura, mas pela doc da API esse preenchimento somente é necessário quando for usar Antifraude, onde no caso de assinaturas não é utilizado, com isso a população desses objetos são opcionais.
#177 
Foi criado mais 2 testes para testar a assinatura por Boleto e Cartão quando não se tem os obejtos Address and Phone populados. Com isso houve necessidade de refatorar os testes para reutilização dos métodos
@xduh @devdrops
=> Fix issue #177

lib/BulkAnticipation/BulkAnticipationHandler.php, lib/BulkAnticipation/Request/BulkAnticipationDelete.php, tests/acceptance/BulkAnticipationContext.php, tests/acceptance/features/bulk_anticipation.feature, tests/unit/BulkAnticipation/Request/BulkAnticipationDeleteTest.php
Corrige o uso para excluir Bulk Anticipations.
**Importante:** a aceitação deste PR exige edição na Wiki.
#149
Adição de testes de aceitação.
=> Correções para DELETE /bulk_anticipations/

lib/SplitRule/SplitRule.php, lib/SplitRule/SplitRuleHandler.php, lib/Transaction/CreditCardTransaction.php, lib/Transaction/TransactionHandler.php, tests/acceptance/SplitRuleContext.php, tests/unit/SplitRule/SplitRuleHandlerTest.php
Adicionado possibilidade de enviar via SplitHandler a flag de `charge_remainder` para especificar de qual regra de split será cobrado os centavos a mais da transação ao invés de deixar sempre na primeira regra de split.
https://github.com/pagarme/pagarme-php/issues/190
Atualizado o teste de aceitação para verificar que as transações continuam sendo criadas corretamente com o "novo parâmetro" e criado testes unitários para verificar que unidade e os métodos estão retornando os dados corretamente.
@devdrops @xduh @ricardotulio
=> V3 add charge remainder split rule

lib/Subscription/Request/SubscriptionUpdate.php, lib/Subscription/SubscriptionBuilder.php, lib/Subscription/SubscriptionHandler.php, lib/Subscription/SubscriptionMemento.php, tests/acceptance/SubscriptionContext.php, tests/acceptance/features/subscription.feature, tests/unit/Subscription/Request/SubscriptionUpdateTest.php, tests/unit/Subscription/SubscriptionBuilderTest.php
It's not mandatory to send all parameters to the update. It's possible to change,
for instance, only the plan_id without to alter the card or the payment method.
To implement it, we use the "memento pattern" instead to make a new request of
the early data subscription.
Changes the "plan_id" parameter name. Use "plan_id" instead of "plan" because the body
of request with "plan" is not accepted by API in the route PUT /subscriptions/:id.
Sends the payment method "credit_card" when "card_id" is inform, because the API
require the payment method together to this update.
Create methods to load the card, plan and payment method with specific validations
to be attached in the body of the request.
Changes unit tests and creates behaviour tests.
=> Changes the mandatory parameters to update subscription route

lib/Subscription/Request/SubscriptionCreate.php, lib/Transaction/Request/TransactionCreate.php, tests/acceptance/SubscriptionContext.php, tests/acceptance/TransactionContext.php, tests/acceptance/features/subscription.feature, tests/acceptance/features/transaction.feature, tests/unit/Subscription/Request/CardSubscriptionCreateTest.php, tests/unit/Transaction/Request/CreditCardTransactionCreateTest.php
Esse PR visa permitir que sejam enviados clientes já existentes na base de dados do Pagar.me na criação de uma nova transação ou assinatura, fazendo com que o mesmo não seja criado repetidamente (se aplica as versões v2017-07-17 e 2017-08-28 da API).
None.
Executando o seguinte trecho de código o `customer_id` retornado na resposta deverá ser o mesmo do objeto `customer` enviado, ou seja, não criando um cliente repetido:
```php
<?php
$card = $pagarMe->card()->create(
'4242424242424242',
'Shagaru Magala',
'0722'
);
$customer = $pagarMe->customer()->get(CUSTOMER_ID);
$amount = 1000;
$installments = 1;
$capture = false;
$postbackUrl = null;
$metadata = ['idProduto' => 13933139];
$transaction = $pagarMe->transaction()->creditCardTransaction(
$amount,
$card,
$customer,
$installments,
$capture, …
```
=> feature: add customer id to transaction and subscription payload

lib/Transaction/BoletoTransaction.php, lib/Transaction/Request/BoletoTransactionCreate.php, tests/unit/Transaction/Request/BoletoTransactionCreateTest.php
Adiciona o campo `soft_descriptor` para transações de boleto bancário através do parâmetro `$extraAttributtes`;
PR criado por solicitação de um cliente =)
=> add softdescriptor to boleto transaction

lib/Customer/CustomerBuilder.php, lib/Transaction/TransactionBuilder.php, tests/acceptance/BulkAnticipationContext.php, tests/acceptance/TransactionContext.php, tests/unit/Customer/CustomerBuilderTest.php
After create a transaction the Sdk builds an object transaction with the API response, but this object have `Customer` and `Card` as a `stdClass`. This PR fix this building the correct `Customer` and `Card` for each one.
This closes #249, closes #216 and closes #199 
<!Descreva aqui todos os detalhes realizados para assegurar o Pull Request. Coloque todos os dados possíveis: versões dos recursos, módulos extras adicionados ao teste :)>
<!NÃO SE ESQUEÇA DE: Marcar um dos desenvolvedores do Pagar.me para review.>
=> Fix wrong object type after create a transaction

lib/Card/CardHandler.php, lib/Card/Request/CardCreate.php, tests/acceptance/CardContext.php, tests/acceptance/features/card.feature, tests/unit/Card/Request/CardCreateTest.php
Este PR tem como seu objetivo permitir que o `cardCvv` também possa ser enviado na criação de um novo cartão, porém sem fazer com que o mesmo se torne obrigatório. Por mais que essa informação não seja obrigatória para que um cartão seja criado, ainda assim a possibilidade de se passar a mesma deveria existir.
None.
Foi validado se o `card_cvv` consta no `payload` de criação de um novo objeto `card`, assim como se um novo cartão válido é criado ao se passar o parâmetro.
=> feature: add cvv to card payload

.travis.yml, tests/acceptance/BulkAnticipationContext.php
The bulk anticipation tests fails in some days of the week because it
count +5 days and +6 days from current date time, and the anticipation
must be in a business day. This PR fix this by validating the week day
and changing the count if the day is a weekend.
This PR also fix some Github authentication errors by changing composer config and clearing cache.
=> bulkanticipation: fix bulk anticipations tests

lib/Transaction/AbstractTransaction.php, lib/Transaction/Request/TransactionCreate.php, tests/unit/CaseConverterTest.php, tests/unit/Transaction/Request/BoletoTransactionCreateTest.php, tests/unit/Transaction/Request/CreditCardTransactionCreateTest.php, tests/unit/Transaction/Request/FakeReferenceKey.php
Add the `reference_key` attribute `AbstractTransactions`. That will be
usefull because this attribute avoid transactions duplication
accidentally. This attribute should have an unique value and has 20
caracters at least.
Unit tests to validate the payload
=> Add reference key to transactions objects

lib/Client.php, lib/PagarMe.php, tests/unit/ClientTest.php
Theres a big difference between `5.*` and `6.*` guzzle majors. So, in the `PagarMe\Sdk\Client::buildRequest` method the sdk should instantiate the correct requests objects accordingly its contracts, in this case twice: `\GuzzleHttp\Message\Request` and `\GuzzleHttp\Psr7\Request`.
If the user define request options, and use guzzle `5.*` this options should be within the request object. If the major is `6.*` the options should be informed on `\GuzzleHttp\Client::send()` method as a second argument.
This fixes the described behavior above creating a new `PagarMe\Sdk\Client::$requestOptions` property and informing it on the right places.
No new tests was created but, the new options is validated on existent tests
=> Fix request timeout on "legacy" guzzle versions

src/Endpoints/Transactions.php, src/Routes.php, tests/unit/Endpoints/PagarMeTestCase.php, tests/unit/Endpoints/TransactionsTest.php, tests/unit/Mocks/CalculateInstallmentsMock.json, tests/unit/Mocks/EventListMock.json, tests/unit/Mocks/OperationListMock.json, tests/unit/RoutesTest.php
This PR add the transaction missing endpoints
- payables
- operations
- collect_payment
- events
- simulateStatus (PUT in `/transactions/:id`)
- calculate_installments_amount
No issue.
Unit tests
For a better review, see the commits instead the full PR
=> transactions: add missing endpoints

lib/Customer/CustomerBuilder.php, tests/unit/Customer/CustomerBuilderTest.php
Não é possível capturar customers sem endereço ou telefone. 
#304 , #278 
Utilizando api key de teste: 
1. Chamando  `customer()->get($id)`, 
2. Customer existe, porém a resposta vem sem endereço e telefone.
3. Erro retornado:
```
[2018-09-16 17:44:21] production.ERROR: Undefined offset: 0 {"exception":"[object] 
(ErrorException(code: 0): Undefined offset: 0 at ...vendor/pagarme/pagarme-
php/lib/Customer/CustomerBuilder.php:14)
````
=> Fix customer builder

src/Client.php
Muitas pessoas que usam a biblioteca estão recebendo o erro
```
Fatal error: Call to a member function getBody() on null in vendor\pagarme\pagarme-php\src\ResponseHandler.php on line 38
```
Isso ocorre pois o tratamento da exceção estava sendo feito de forma errada. A biblioteca espera uma exceção do tipo `GuzzleHttp\Exception\ClientException`, mas é enviada uma `Exception`, que não possui o método `getResponse()->getBody();`
Sem issue.
Testes unitários, para garantir que ClientException sejam redirecionadas para o local correto.
=> response handler: fix client exception handler

lib/Client.php
Identificamos um edge case, onde um cliente teve problemas ao utilizar o https://github.com/pagarme/pagarme-magento (que depende deste sdk). Especificamente neste caso duas majors versions do guzzle estavam presentes no ambiente. Dessa forma, a verificação alterada neste PR se tornava sempre verdadeira fazendo com o que a interface pública do Guzzle (neste caso divergente dadas as duas versões) fosse chamada erroneamente.
Este PR reorganiza a prioridade dessa verificação dando prioridade à versões mais recentes e em caso de versões mais antigas do guzzle, adiciona uma verificação para validar a existência do método chamado.
Não há
Testes manuais. Os testes unitários já existentes garantem o funcionamento do fluxo mencionado
=> Reordena a verificação de compatibilidade entre versões do Guzzle

lib/Transaction/AbstractTransaction.php
Adiciona o status `analyzing` na interface `AbstractTransaction` e a const `isAnalyzing`. Essa alteração é dependência para a adição do `analyzing` nas plataformas Magento e Woocommerce.
<!Insira aqui o contexto/motivo deste Pull Request.>
<!Descreva aqui todos os detalhes realizados para assegurar o Pull Request. Coloque todos os dados possíveis: versões dos recursos, módulos extras adicionados ao teste :)>
<!NÃO SE ESQUEÇA DE: Marcar um dos desenvolvedores do Pagar.me para review.>
=> transaction: create analyzing status

lib/PagarMe.php, lib/RequestHeaders.php, tests/unit/RequestHeadersTest.php
Adiciona os headers `X-PagarMe-User-Agent` e `User-Agent` nas requisições.
Isso nos permitirá colher métricas através de logs e do banco de dados
Manuais e unitários
=> headers: add X-PagarMe-User-Agent and User-Agent

.circleci/config.yml, docker-compose.yml, docker/php7/Dockerfile, psalm-baseline.xml, psalm.xml, src/Anonymous.php, src/Client.php, src/Endpoints/Customers.php, src/Exceptions/PagarMeException.php, src/ResponseHandler.php
**O que é o Psalm**
Uma ferramenta de análise estática de código. O objetivo é através dessa análise identificar erros de implementação, validar inputs/outputs de métodos de acordo com os tipos definidos etc.
**Como funciona**
O psalm tem como requisito o php7 apesar de poder ser utilizado em projetos baseados em php5.6. Dessa forma foi adicionado um novo container com php7 que instala o composer e o psalm (globalmente). A validação é feita executando o comando `docker-compose run php7 psalm`
Não há issue
Validação de que nada foi quebrado usando os unitários existentes.
=> Integra o psalm para validação de qualidade do código

src/Client.php, tests/unit/ClientTest.php
Permite que headers customizados sejam enviados para a API.
Atualmente os headers estão sendo substituidos, fazendo com que a SDK não funcione com diversas versões de API.
#366 
Testes unitarios, garantindo a presença dos headers enviados.
=> fix: custom headers

src/Client.php, src/PagarMe.php, tests/unit/ClientTest.php
Com o intuito de criar a possibilidade de monitorar o uso de nossos SDKs, esse PR tem o objetivo de padronizar o **header X-PagarMe-User-Agent**, enviando a versão do sdk em uso.
Diferente [da v3](https://github.com/pagarme/pagarme-php/blob/V3/lib/PagarMe.php#L28), pelo que vi a v4 ainda não tinha a versão do SDK armazenada em uma _constant_. Adicionei isso também nesse PR.
Issue relacionada: https://github.com/pagarme/Support/issues/181
=> Padronização do header X-PagarMe-User-Agent V4

composer.json, lib/PagarMe.php, lib/RequestHeaders.php, tests/acceptance/TransactionContext.php, tests/acceptance/features/transaction.feature, tests/unit/RequestHeadersTest.php
Com o intuito de criar a possibilidade de monitorar o uso de nossos SDKs, esse PR tem o objetivo de padronizar o **header X-PagarMe-User-Agent**, enviando a versão do PHP em uso, além da versão do SDK.
\
Obs.: Foi necessário ajustar alguns testes que nem tem relação com esse PR, devido à config da company de teste não aceitar parcelamento na bandeira Diners e também aos Payables agora serem async com o Atlas. Também estava ocorrendo incompatibilidade com o phpunit 4, guzzlehttp e a versão 7.2 do PHP:
`Fatal error: Declaration of Mock_Client_8cee1f51::sendAsync(Psr\Http\Message\RequestInterface $request, array $options = Array) must be compatible with GuzzleHttp\Client::sendAsync(Psr\Http\Message\RequestInterface $request, array $options = Array): GuzzleHttp\Promise\PromiseInterface in …
=> Padronização do header X-PagarMe-User-Agent V3
