- behat.yml
- lib/PagarMe.php
- lib/SplitRule/SplitRule.php
- lib/SplitRule/SplitRuleCollection.php
- lib/SplitRule/SplitRuleHandler.php
- lib/Transaction/AbstractTransaction.php
- lib/Transaction/Request/TransactionCreate.php
- lib/Transaction/TransactionHandler.php
- tests/acceptance/SplitRuleContext.php
- tests/acceptance/features/recipient.feature
- tests/acceptance/features/split_rule.feature
- tests/unit/PagarMeTest.php
- tests/unit/SplitRule/SplitRuleHandlerTest.php
- tests/unit/Transaction/Request/BoletoTransactionCreateTest.php
- tests/unit/Transaction/Request/CreditCardTransactionCreateTest.php
- Criar transação com SplitRules 
- Receber SplitRule na transação
> Feature split rule

- lib/BankAccount/BankAccount.php
- lib/Recipient/RecipientHandler.php
- lib/Recipient/Request/RecipientCreate.php
- lib/Transaction/Request/BoletoTransactionRefund.php
- lib/Transaction/TransactionHandler.php
- tests/acceptance/RecipientContext.php
- tests/acceptance/SplitRuleContext.php
- tests/unit/Recipient/RecipientHandlerTest.php
- tests/unit/Recipient/Request/RecipientCreateTest.php
- tests/unit/Recipient/Request/RecipientUpdateTest.php
- tests/unit/Transaction/Request/BoletoTransactionRefundTest.php
- tests/unit/Transaction/TransactionHandlerTest.php
Move 'Account' references to 'BankAccount'
> Refactor bank account

- behat.yml
- lib/Customer/AddressBuilder.php
- lib/Customer/CustomerHandler.php
- lib/Customer/PhoneBuilder.php
- lib/PagarMe.php
- lib/Subscription/Request/BoletoSubscriptionCreate.php
- lib/Subscription/Request/CardSubscriptionCreate.php
- lib/Subscription/Request/SubscriptionCancel.php
- lib/Subscription/Request/SubscriptionCreate.php
- lib/Subscription/Request/SubscriptionGet.php
- lib/Subscription/Request/SubscriptionList.php
- lib/Subscription/Request/SubscriptionTransactionsGet.php
- lib/Subscription/Request/SubscriptionUpdate.php
- lib/Subscription/Subscription.php
- lib/Subscription/SubscriptionHandler.php
- lib/Transaction/TransactionBuilder.php
- lib/Transaction/TransactionHandler.php
- tests/acceptance/SubscriptionContext.php
- tests/acceptance/features/plan.feature
- tests/acceptance/features/subscription.feature
- tests/unit/PagarMeTest.php
- tests/unit/Subscription/Request/BoletoSubscriptionCreateTest.php
- tests/unit/Subscription/Request/CardSubscriptionCreateTest.php
- tests/unit/Subscription/Request/SubscriptionCancelTest.php
- tests/unit/Subscription/Request/SubscriptionGetTest.php
- tests/unit/Subscription/Request/SubscriptionListTest.php
- tests/unit/Subscription/Request/SubscriptionTransactionGetTest.php
- tests/unit/Subscription/Request/SubscriptionUpdateTest.php
Criando assinaturas
Retornando uma assinatura
Retornando assinaturas
Atualizando uma assinatura
Cancelando uma assinatura
Transações em uma assinatura
> Feature subscription

- behat.yml
- lib/Company/CompanyHandler.php
- lib/Company/Request/CompanyInfo.php
- lib/PagarMe.php
- tests/acceptance/CompanyContext.php
- tests/acceptance/features/company.feature
- tests/unit/Company/Request/CompanyInfoTest.php
- tests/unit/PagarMeTest.php
> Feature company

- behat.yml
- lib/PagarMe.php
- lib/Payable/Payable.php
- lib/Payable/PayableHandler.php
- lib/Payable/Request/PayableGet.php
- lib/Payable/Request/PayableList.php
- tests/acceptance/PayableContext.php
- tests/acceptance/features/payable.feature
- tests/unit/PagarMeTest.php
- tests/unit/Payable/Request/PayableGetTest.php
- tests/unit/Payable/Request/PayableListTest.php
Objeto payable
Retornando recebíveis
Retornando um recebível
> Feature payables

- lib/BulkAnticipation/BulkAnticipation.php
- lib/BulkAnticipation/BulkAnticipationHandler.php
- lib/BulkAnticipation/Request/BulkAnticipationCancel.php
- lib/BulkAnticipation/Request/BulkAnticipationConfirm.php
- lib/BulkAnticipation/Request/BulkAnticipationCreate.php
- lib/BulkAnticipation/Request/BulkAnticipationDelete.php
- lib/BulkAnticipation/Request/BulkAnticipationLimits.php
- lib/BulkAnticipation/Request/BulkAnticipationList.php
- lib/MicrosecondsFormatter.php
- lib/PagarMe.php
- lib/Request.php
- tests/unit/BulkAnticipation/Request/BulkAnticipationCancelTest.php
- tests/unit/BulkAnticipation/Request/BulkAnticipationConfirmTest.php
- tests/unit/BulkAnticipation/Request/BulkAnticipationCreateTest.php
- tests/unit/BulkAnticipation/Request/BulkAnticipationDeleteTest.php
- tests/unit/BulkAnticipation/Request/BulkAnticipationLimitsTest.php
- tests/unit/BulkAnticipation/Request/BulkAnticipationListTest.php
- tests/unit/MicrosecondsFormatterTest.php
- tests/unit/PagarMeTest.php
Objeto bulk_anticipation
Criando uma antecipação
Obtendo os limites de antecipação
Confirmando uma antecipação building
Cancelando uma antecipação pending
Deletando uma antecipação building
Retornando todas as antecipações
> Feature bulk anticipation

- lib/Event/Event.php
- lib/Transaction/Request/TransactionEvents.php
- lib/Transaction/TransactionHandler.php
- tests/acceptance/TransactionContext.php
- tests/acceptance/features/transaction.feature
- tests/unit/Transaction/Request/TransactionEventsTest.php
Event Object
Retornando todos os eventos de uma transação
> Return transaction events

- behat.yml
- lib/PagarMe.php
- lib/Zipcode/Request/ZipcodeInfoGet.php
- lib/Zipcode/ZipcodeHandler.php
- tests/acceptance/ZipcodeContext.php
- tests/acceptance/features/zipcode.feature
- tests/unit/PagarMeTest.php
- tests/unit/Zipcode/Request/ZipcodeGetTest.php
> Get Zipcode info

- behat.yml
- lib/PagarMe.php
- lib/Search/Request/SearchGet.php
- lib/Search/SearchHandler.php
- lib/Transaction/Request/CreditCardTransactionCreate.php
- lib/Transaction/Request/TransactionCreate.php
- lib/Transaction/TransactionHandler.php
- tests/acceptance/Helper/CustomerDataProvider.php
- tests/acceptance/SearchContext.php
- tests/acceptance/SplitRuleContext.php
- tests/acceptance/TransferContext.php
- tests/acceptance/features/search.feature
- tests/unit/PagarMeTest.php
- tests/unit/Search/Request/SearchGetTest.php
- tests/unit/Transaction/Request/BoletoTransactionCreateTest.php
- tests/unit/Transaction/Request/CreditCardTransactionCreateTest.php
Enable /search endpoint
Fix metadata param on transactions
> Feature search

- composer.json
- composer.lock
Specifying minimal php version on composer
> Add php version to composer.json

- lib/Balance/BalanceHandler.php
- lib/BankAccount/BankAccountHandler.php
- lib/Calculation/CalculationHandler.php
- lib/Recipient/RecipientHandler.php
- lib/Subscription/SubscriptionHandler.php
- lib/Transaction/TransactionHandler.php
- lib/Transfer/TransferHandler.php
> Normalize variable names on handlers

- tests/acceptance/RecipientContext.php
- tests/acceptance/features/recipient.feature
Add skiping tests on recipient feature, on creating recipients
> Add missing tests on recipient creation

- composer.json
- composer.lock
- lib/Client.php
- lib/PagarMe.php
- tests/unit/ClientTest.php
Reverts pagarme/pagarme-php#107
> Revert "Add sentry"

- lib/Transaction/BoletoTransaction.php
- lib/Transaction/Request/TransactionGet.php
Correções das seguintes issues:
https://github.com/pagarme/pagarme-php/issues/116
https://github.com/pagarme/pagarme-php/issues/117
> "boleto_url" / "boleto_barcode" e busca de transação

- lib/Client.php
> Fix for SensiolabsInsight minor issue

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Add template when creating isssues and pull requests, fixing #140
> Add issues and pull requests template

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Cria arquivos de template para criação de issue e pull request.
Issue #140
> Move ISSUE_TEMPLATE.md e PULL_REQUEST_TEMPLATE.md para o branch master

- README.md
Não tinha essa informação antes
> Adicionando informação sobre wiki no readme

- README.md
Adotar o padrão de headers para README do Pagar.me.
> Padrão de Header

- lib/Transaction/Request/TransactionCreate.php
- tests/unit/Transaction/Request/BoletoTransactionCreateTest.php
- tests/unit/Transaction/Request/CreditCardTransactionCreateTest.php
Corrige problema ao transacionar sem dados de endereço e telefone do customer
#138 
Adicionados testes unitários
> Transacionar sem dados do customer

- lib/Transaction/Request/CreditCardTransactionCreate.php
- tests/acceptance/TransactionContext.php
- tests/unit/Transaction/Request/CreditCardTransactionCreateTest.php
Fix #166 
#166 
Adicionado teste unitário
> Corrige envio do paramêtro soft_descriptor

- lib/BankAccount/BankAccount.php
- lib/BankAccount/BankAccountHandler.php
- lib/BankAccount/Request/BankAccountCreate.php
- tests/acceptance/BankAccountContext.php
- tests/acceptance/features/bank_account.feature
- tests/unit/BankAccount/Request/BankAccountCreateTest.php
Corrige problema da issue #144 
#144 
Adicionado teste unitário e de comportamento
> Especificar tipo de conta bancária durante a criação

- lib/Card/Card.php
- tests/acceptance/CardContext.php
- tests/acceptance/features/card.feature
- tests/unit/Card/CardBuilderTest.php
Closes #175. The Card entity did not have an expiration date, now it's
working as expected.
#175 
Adicionei o comportamento novo nos testes unitários e de integração :)
> Fix Card entity with no expiration date

- lib/Transaction/Request/BoletoTransactionRefund.php
- lib/Transaction/TransactionHandler.php
- tests/acceptance/TransactionContext.php
- tests/acceptance/features/transaction.feature
Permite estornar parcialmente transações feitas com boleto.
Testes automatizados de aceitação.
> Estorno parcial de Boleto Transaction

- lib/Subscription/SubscriptionBuilder.php
- tests/unit/Subscription/SubscriptionBuilderTest.php
Corrige o problema de análise/transformação de assinaturas sem transações
O mesmo que o #182, só que burlando o check maluco do scrutinizer
#151 
Adicionado teste unitário
>  Fix/get subscription error

- tests/unit/Recipient/Request/RecipientOperationsTest.php
Corrige testes rodando sobre 5.6 e 7.0 do PHP
Corrigido teste em: Request/RecipientOperationsTest
> Fix recipient tests

- lib/Subscription/Request/BoletoSubscriptionCreate.php
- lib/Subscription/Request/CardSubscriptionCreate.php
- lib/Subscription/Request/SubscriptionCreate.php
- lib/Subscription/SubscriptionHandler.php
- tests/unit/Subscription/Request/BoletoSubscriptionCreateTest.php
- tests/unit/Subscription/Request/CardSubscriptionCreateTest.php
PR para o SDK fazer Split de assinaturas
#201
Foi feito 4 novos testes, 2 para cada método de pagamento(cartão boleto) onde foi é feito o Split ou por porcentagem ou por valores.
@xduh @devdrops @vgsmith
> Fix issue 201

- lib/Transaction/BoletoTransaction.php
- lib/Transaction/Request/BoletoTransactionCreate.php
- tests/acceptance/TransactionContext.php
- tests/acceptance/features/transaction.feature
- tests/unit/Transaction/Request/BoletoTransactionCreateTest.php
Adiciona o parâmetro async à transações de boleto bancário
#212
> Added Async to Boleto Transaction

- tests/acceptance/SubscriptionContext.php
<!Insira aqui o contexto/motivo deste Pull Request.>
Corrige os testes de aceitação de assinaturas ao passar formas de pagamento na criação de um novo plano.
#227 
<!Descreva aqui todos os detalhes realizados para assegurar o Pull Request. Coloque todos os dados possíveis: versões dos recursos, módulos extras adicionados ao teste :)>
<!NÃO SE ESQUEÇA DE: Marcar um dos desenvolvedores do Pagar.me para review.>
> fix: acceptance-tests

- lib/Transaction/BoletoTransaction.php
- lib/Transaction/Request/BoletoTransactionCreate.php
- tests/unit/Transaction/Request/BoletoTransactionCreateTest.php
Adiciona o parâmetro `boleto_instructions` para transações com boleto bancário como forma de pagamento.
> Feature: add boleto instructions to boleto transactions

- .travis.yml
- lib/Pagarme/PagarMe.php
- tests/PagarMe/Subscription.php
- tests/PagarMe/Transaction.php
<!Insira aqui o contexto/motivo deste Pull Request.>
Corrige os erros de validação de certificado `Peer's Certificate issuer is not recognized`
Não possui Issue.
> Fix certificate validation

- lib/Transaction/Request/TransactionPayables.php
- lib/Transaction/TransactionHandler.php
- tests/acceptance/TransactionContext.php
- tests/acceptance/features/transaction.feature
- tests/unit/Transaction/Request/TransactionPayablesTest.php
Seguindo: https://github.com/pagarme/pagarme-php/pull/247
> Retornar os payables de uma transaction

- lib/PagarMeException.php
- tests/unit/ClientTest.php
This pull request intends to resolve issue #248 
This closes #248
> pagarmeexception: fix json_encode twice

- .circleci/config.yml
- composer.json
- Adiciona configuração do CircleCI
- Remove hook de pre-commit
- Adiciona dependência do codesniffer em `dev`
> circleci: add circleci

- src/Client.php
- src/Endpoints/BankAccounts.php
- src/Routes.php
- tests/unit/BankAccountsTest.php
- tests/unit/Mocks/BankAccountListMock.json
- tests/unit/Mocks/BankAccountMock.json
- tests/unit/RoutesTest.php
> V4: add bank_accounts endpoints

- src/Client.php
- src/Endpoints/Plans.php
- src/Routes.php
- tests/unit/Mocks/PlanListMock.json
- tests/unit/Mocks/PlanMock.json
- tests/unit/PlansTest.php
- tests/unit/RoutesTest.php
Adiciona o endpoint de planos ao SDK V4.
https://github.com/pagarme/seals/issues/185
Testes unitários
> V4: add plans endpoints

- src/Client.php
- src/Endpoints/Transfers.php
- src/Routes.php
- tests/unit/Endpoints/TransfersTest.php
- tests/unit/Mocks/TransferListMock.json
- tests/unit/Mocks/TransferMock.json
- tests/unit/RoutesTest.php
- Create Transfers;
- Get and list Transfers;
- Cancel Transfers.
Automated tests only.
> transfer: add communication with /transfers

- src/Client.php
- src/Endpoints/Refunds.php
- src/Routes.php
- tests/unit/Endpoints/RefundsTest.php
- tests/unit/Mocks/RefundsMock.json
- tests/unit/RoutesTest.php
Possibilita o acesso ao endpoint de estornos. Assim é possível visualizar todos os estornos que ocorreram em sua conta.
Sem Issue
Testes unitários
> endpoints: add the refunds endpoint

- src/Client.php
- src/Endpoints/Chargebacks.php
- src/Routes.php
- tests/unit/Endpoints/ChargebacksTest.php
- tests/unit/Mocks/ChargebacksMock.json
- tests/unit/RoutesTest.php
Add chargebacks endpoint, with it the developer can see all account's chargebacks.
No Issue.
Unit tests.
> endpoints: add the chargebacks endpoint

- README.md
Adiciona documentação com exemplos de código de como utilizar a versão 4 do SDK
> Create version documentation

- README.md
Adiciona instruções de uso na branch V3.
Sem issue.
Sem testes.
> readme: adds usage instructions

- README.md
Adiciona instruções de uso da SDK no README
Sem Issue
Sem testes.
> add v2 readme instructions

- README.md
Corrige o exemplo de cálculo de juros do README
> readme: fix installments example

- src/Client.php
- src/Endpoints/Endpoint.php
- src/Endpoints/Transactions.php
- src/PagarMeException.php
- src/Routes.php
Baseado no report do PHPStan, ajusta os dockblocks do projeto
Sem issue
Unitários
> project: adjust dockblocs

- lib/Pagarme/RestClient.php
Adiciona os headers `X-PagarMe-User-Agent` e `User-Agent` nas requisições.
Isso nos permitirá colher métricas através de logs e do banco de dados
Testes manuais verificando os logs
> Adiciona X-PagarMe-User-Agent nas requisições da V2

- src/Exceptions/PagarMeException.php
- tests/unit/ClientTest.php
- tests/unit/Exceptions/PagarmeExceptionTest.php
Concatena os dados retornados pela API do Pagar.me em uma única string, tornando mais claro o problema ocorrido.
Resolves #317
#317 
unitários
> Melhora a clareza das mensagens de exception

- README.md
- src/Client.php
- src/Endpoints/Search.php
- src/Routes.php
- tests/unit/Endpoints/SearchTest.php
- tests/unit/Mocks/SearchListMock.json
- tests/unit/RoutesTest.php
Criei essa pull request para adicionar a feature da rota /search (Elasticsearch) nesse SDK.
Testei a nova feature e adicionei o exemplo no README.md. Testei também as outras features e continuam funcionando normalmente.
> nova feature da rota /search (elasticsearch)

- lib/PagarMe.php
- tests/acceptance/TransactionContext.php
Bump version to 3.9.0
PR que adicionou o pix na v3: https://github.com/pagarme/pagarme-php/pull/379
> bump version to 3.9.0

- src/Endpoints/Recipients.php
- src/Routes.php
- tests/unit/Endpoints/RecipientsTest.php
- tests/unit/Mocks/KycLinkMock.json
- tests/unit/RoutesTest.php
Esse PR tem como objetivo a criação de uma nova rota que gera um link kyc.
N/A
> feat: add new generate kyc link route v4

- README.md
- lib/Recipient/RecipientHandler.php
- lib/Recipient/Request/RecipientGenerateKycLink.php
- tests/unit/Recipient/Request/RecipientGenerateKycLinkTest.php
Esse PR tem como objetivo a criação de uma nova rota que gera um link kyc.
N/A
Tentei rodar o composer test mas está dando erro em uma trait que não tem nada haver com o que foi adicionado.
> feat: add generate kyc link route v3

- src/Client.php
- src/RequestHandler.php
- tests/unit/RequestHandlerTest.php
<!Insira aqui o contexto/motivo deste Pull Request.>
<!Descreva aqui todos os detalhes realizados para assegurar o Pull Request. Coloque todos os dados possíveis: versões dos recursos, módulos extras adicionados ao teste :)>
<!NÃO SE ESQUEÇA DE: Marcar um dos desenvolvedores do Pagar.me para review.>
> chore: alter api_key to basic auth
